"""MDP interface for the standalone sweep task."""

from isaaclab.envs.mdp import (
    action_rate_l2,
    generated_commands,
    joint_effort,
    joint_pos,
    joint_vel,
    joint_vel_l2,
    last_action,
    randomize_rigid_body_mass,
    randomize_rigid_body_material,
    reset_joints_by_offset,
    reset_scene_to_default,
    time_out,
)

from .actions import IndependentSweepOscAction, IndependentSweepOscActionCfg
from .common import PHASE_HOME, PHASE_REACH, PHASE_SWEEP
from .commands import FeasibleSweepHomeCommand, FeasibleSweepHomeCommandCfg
from .events import (
    TARGET_SIZE_BUFFER,
    print_reset_physics_info,
    randomize_target_cube_size,
    reset_variable_size_target,
)
# Start/goal visualization is intentionally disabled.
# from .events import create_sweep_position_visualizers
from .observations import (
    MaskedUniformNoiseCfg,
    VectorUniformNoiseCfg,
    end_effector_pose_b,
    initial_target_pose_b,
    target_contact_point_b,
    task_phase,
    virtual_ft_wrench_b,
)
from .rewards import contact, home_return, push, reaching
from .rewards_detailed import (
    commanded_joint_effort_l2,
    failure_termination_penalty,
    ft_torque_excess,
    home_contact_penalty,
    home_eef_clearance,
    home_goal_hold_error,
    home_joint_error,
    home_joint_pose_tracking,
    home_object_displacement,
    home_object_speed,
    home_success_bonus,
    home_time,
    reach_pose_error,
    reach_pose_tracking,
    sweep_contact,
    sweep_endpoint_error,
    sweep_forward_progress,
    sweep_lateral_error,
    sweep_overshoot,
    sweep_stopped_at_goal,
    sweep_velocity_tracking,
    torque_saturation,
)
from .terminations import (
    ContactLostTooLong,
    HomeAfterSweepSuccess,
    HomeContactAfterRelease,
    arm_joint_speed_limit,
    excessive_ft_wrench,
    object_disturbed_during_home,
    object_inside_gripper,
    robot_self_collision,
    robot_shelf_collision,
    target_invalid_pose,
)

__all__ = [
    "ContactLostTooLong",
    "FeasibleSweepHomeCommand",
    "FeasibleSweepHomeCommandCfg",
    "HomeAfterSweepSuccess",
    "HomeContactAfterRelease",
    "IndependentSweepOscAction",
    "IndependentSweepOscActionCfg",
    "MaskedUniformNoiseCfg",
    "PHASE_HOME",
    "PHASE_REACH",
    "PHASE_SWEEP",
    "TARGET_SIZE_BUFFER",
    "VectorUniformNoiseCfg",
    "action_rate_l2",
    "arm_joint_speed_limit",
    "contact",
    "commanded_joint_effort_l2",
    # "create_sweep_position_visualizers",
    "end_effector_pose_b",
    "excessive_ft_wrench",
    "failure_termination_penalty",
    "ft_torque_excess",
    "generated_commands",
    "home_return",
    "home_contact_penalty",
    "home_eef_clearance",
    "home_goal_hold_error",
    "home_joint_error",
    "home_joint_pose_tracking",
    "home_object_displacement",
    "home_object_speed",
    "home_success_bonus",
    "home_time",
    "initial_target_pose_b",
    "joint_effort",
    "joint_pos",
    "joint_vel",
    "joint_vel_l2",
    "last_action",
    "object_disturbed_during_home",
    "object_inside_gripper",
    "push",
    "print_reset_physics_info",
    "randomize_rigid_body_mass",
    "randomize_rigid_body_material",
    "randomize_target_cube_size",
    "reaching",
    "reach_pose_error",
    "reach_pose_tracking",
    "reset_joints_by_offset",
    "reset_scene_to_default",
    "reset_variable_size_target",
    "robot_self_collision",
    "robot_shelf_collision",
    "sweep_contact",
    "sweep_endpoint_error",
    "sweep_forward_progress",
    "sweep_lateral_error",
    "sweep_overshoot",
    "sweep_stopped_at_goal",
    "sweep_velocity_tracking",
    "target_contact_point_b",
    "target_invalid_pose",
    "task_phase",
    "time_out",
    "torque_saturation",
    "virtual_ft_wrench_b",
]
